FROM nginx:1.27.3-alpine
WORKDIR /app
COPY ./app/index.html ./index.html
EXPOSE 80/tcp
RUN apk update && apk upgrade && apk search curl && apk add curl
RUN apk add htop
RUN apk add wget

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]