FROM nginx:1.27.3-alpine
WORKDIR /app
COPY ./app/index.html ./index.html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ARG APP_VERSION=1.0.0

RUN apk update && apk upgrade && apk search curl && apk add curl
RUN apk add htop
RUN apk add wget

STOPSIGNAL SIGTERM
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]